---
title: Example analysis
format: 
    pdf:
      keep-tex: true
---



## Linear model, smoking is the exposure, birthweight in grams the outcome
```{r}
#| echo: true

infunc_confint <- function(ofit, wfit, exposurename, outcomename) {
  
  
  data <- ofit$data
  data1 <- data0 <- data
  data1[[exposurename]] <- 1
  data0[[exposurename]] <- 0
  
  n <- nrow(data1)
  
  est1f <- mean(predict(ofit, newdata = data1, type = "response"))
  est0f <- mean(predict(ofit, newdata = data0, type = "response"))
  
  # refit using unweighted eeqs
  ofitunwt <- glm(ofit$formula, family = ofit$family, 
                 data = data)

  phat <- predict(wfit, type = "response")
 
  
  est1 <- predict(ofitunwt, newdata = data1, type = "response")
  est0 <- predict(ofitunwt, newdata = data0, type = "response")

  XXw <- model.matrix(wfit)
  XXo <- XXo1 <- XXo0 <- model.matrix(ofitunwt)
  XXo1[,exposurename] <- 1
  XXo0[,exposurename] <- 0
  
  ifweight <- t(vcov(wfit) %*% t(sandwich::estfun(wfit)))
  ifout <- t(vcov(ofit) %*% t(sandwich::estfun(ofitunwt)))
  
  
  eifterms1 <- (data[[exposurename]] / phat * (data[[outcomename]] - est1) + (est1 - est1f)) / n
  eifterms0 <- ((1 - data[[exposurename]]) / (1 - phat) * (data[[outcomename]] - est0) + (est0 - est0f)) / n
  
  
  hdot <- family(wfit)$mu.eta(predict(wfit, type = "link"))
  
  gdot0 <- family(ofit)$mu.eta(predict(ofitunwt, newdata = data0, type = "link"))
  gdot1 <- family(ofit)$mu.eta(predict(ofitunwt, newdata = data1, type = "link"))
  
  Kterm1 <- (-1/n) * matrix(((data[[exposurename]] * hdot) / phat^2) * 
                              (data[[outcomename]] - est1), nrow = 1, ncol = n) %*%
    XXw
  Kterm0 <- (1/n) * matrix((((1 - data[[exposurename]]) * hdot) / (1 - phat)^2) * 
                             (data[[outcomename]] - est0), nrow = 1, ncol = n) %*%
    XXw
  
  Lterm1 <- (1/ n) * matrix(gdot1 * (1 - data[[exposurename]]/phat), nrow = 1, ncol = n) %*% 
    XXo1
  
  Lterm0 <- (1/ n) * matrix(gdot0 * ((1 - data[[exposurename]])/(1 - phat) - 1), nrow = 1, ncol = n) %*% 
    XXo0
  
  fullif1 <- cbind(eifterms1, (ifweight %*% t(Kterm1)), (ifout %*% t(Lterm1)))
  fullif0 <- cbind(eifterms0, (ifweight %*% t(Kterm0)), (ifout %*% t(Lterm0)))
  
  
  estse <- sqrt(sum((rowSums(fullif1) - rowSums(fullif0))^2))
  est <- est1f - est0f
  
  c(lower = est - 1.96 * estse, upper = est + 1.96 * estse)
  
  
}

data <- AF::clslowbwt
head(data)
## propensity score fit

pwfit <- glm(smoker ~ race * age * lwt + I(age^2) + I(lwt^2), data = data, 
             family = "binomial")
phat <- predict(pwfit, type = "response")

data$weight <- data$smoker / phat + (1 - data$smoker) / (1 - phat)
## outcome model

outfit <- glm(bwt ~ smoker * (race + age + lwt) + I(age^2) + I(lwt^2), 
              data = data, family = "gaussian", weights = weight)

## dummy data, where we set X to 0 and 1

data0 <- data1 <- data
data0$smoker <- 0
data1$smoker <- 1

## predicted couterfactuals
Yhat0 <- predict(outfit, newdata = data0, type = "response")
Yhat1 <- predict(outfit, newdata = data1, type = "response")

ATEmean <- mean(Yhat1) - mean(Yhat0)
ATEmean
infunc_confint(outfit, pwfit, "smoker", "bwt")

## CAN Richard Funk?

## separate outcome models, unweighted

ofit1 <- glm(bwt ~ (race + age + lwt) + I(age^2) + I(lwt^2), 
              data = subset(data, smoker == 1), family = "gaussian")

ofit0 <- glm(bwt ~ (race + age + lwt) + I(age^2) + I(lwt^2), 
              data = subset(data, smoker == 0), family = "gaussian")


dr1 <- data$bwt * (data$smoker == 1) / phat - 
  predict(ofit1, newdata = data1, type = "response") * 
  ((data$smoker == 1) - phat) / phat
dr0 <- data$bwt * (data$smoker == 0) / (1 - phat) + 
  predict(ofit0, newdata = data0, type = "response") * 
  ((data$smoker == 1) - phat) / (1 - phat)

ATEfunk <- mean(dr1) - mean(dr0)  
ATEfunk

```


Bootstrap for confidence interval, not echoed

```{r}
#| echo: false
#| warning: false

set.seed(230221)
bootATE <- rep(NA, 1000)
for(i in 1:length(bootATE)) {
## sample ids
  datab <-data[sample(1:nrow(data), nrow(data), replace = TRUE), ]

## propensity score fit

pwfit <- glm(smoker ~ race * age * lwt + I(age^2) + I(lwt^2), data = datab, 
             family = "binomial")
phat <- predict(pwfit, type = "response")

datab$weight <- datab$smoker / phat + (1 - datab$smoker) / (1 - phat)
## outcome model

outfit <- glm(bwt ~ smoker * (race + age + lwt) + I(age^2) + I(lwt^2), 
              data = datab, family = "gaussian", weights = weight)

## dummy data, where we set X to 0 and 1

data0 <- data1 <- datab
data0$smoker <- 0
data1$smoker <- 1

## predicted couterfactuals
Yhat0 <- predict(outfit, newdata = data0, type = "response")
Yhat1 <- predict(outfit, newdata = data1, type = "response")

bootATE[i] <- mean(Yhat1 - Yhat0)

}

quantile(bootATE, c(.025, .975))
```



## Logistic model, smoking is the exposure, low birthweight (birth weight < 2500g) the outcome
```{r}
#| echo: true

## propensity score fit

pwfit <- glm(smoker ~ race * age * lwt + I(age^2) + I(lwt^2), data = data, 
             family = "binomial")
phat <- predict(pwfit, type = "response")

data$weight <- data$smoker / phat + (1 - data$smoker) / (1 - phat)
## outcome model

outfit <- glm(lbw ~ smoker * (race + age + lwt) + I(age^2) + I(lwt^2), 
              data = data, family = "binomial", weights = weight)

## dummy data, where we set X to 0 and 1

data0 <- data1 <- data
data0$smoker <- 0
data1$smoker <- 1

## predicted couterfactuals
Yhat0 <- predict(outfit, newdata = data0, type = "response")
Yhat1 <- predict(outfit, newdata = data1, type = "response")

ATEmean <- mean(Yhat1) - mean(Yhat0)
ATEmean
infunc_confint(outfit, pwfit, "smoker", "lbw")

RRmean <- mean(Yhat1) / mean(Yhat0)
RRmean


## separate outcome models, unweighted

ofit1 <- glm(lbw ~ (race + age + lwt) + I(age^2) + I(lwt^2), 
              data = subset(data, smoker == 1), family = "binomial")

ofit0 <- glm(lbw ~ (race + age + lwt) + I(age^2) + I(lwt^2), 
              data = subset(data, smoker == 0), family = "binomial")


dr1 <- data$lbw * (data$smoker == 1) / phat - 
  predict(ofit1, newdata = data1, type = "response") * 
  ((data$smoker == 1) - phat) / phat
dr0 <- data$lbw * (data$smoker == 0) / (1 - phat) + 
  predict(ofit0, newdata = data0, type = "response") * 
  ((data$smoker == 1) - phat) / (1 - phat)

ATEfunk <- mean(dr1) - mean(dr0)  
RRfunk <- mean(dr1) / mean(dr0)
ATEfunk

RRfunk

```


Bootstrap for confidence interval, not echoed

```{r}
#| echo: false
#| warning: false

set.seed(230221)
bootATE <- bootRR <- rep(NA, 1000)
for(i in 1:length(bootATE)) {
  
   datab <-data[sample(1:nrow(data), nrow(data), replace = TRUE), ]

## propensity score fit

pwfit <- glm(smoker ~ race * age * lwt + I(age^2) + I(lwt^2), data = datab, 
             family = "binomial")
phat <- predict(pwfit, type = "response")

datab$weight <- datab$smoker / phat + (1 - datab$smoker) / (1 - phat)
## outcome model

outfit <- glm(lbw ~ smoker * (race + age + lwt) + I(age^2) + I(lwt^2), 
              data = datab, family = "binomial", weights = weight)

## dummy data, where we set X to 0 and 1

data0 <- data1 <- datab
data0$smoker <- 0
data1$smoker <- 1

## predicted couterfactuals
Yhat0 <- predict(outfit, newdata = data0, type = "response")
Yhat1 <- predict(outfit, newdata = data1, type = "response")

bootATE[i] <- mean(Yhat1 - Yhat0)
bootRR[i] <- mean(Yhat1) / mean(Yhat0)
}

quantile(bootATE, c(.025, .975))

quantile(bootRR, c(.025, .975))
```


